# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-19 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beads', '0003_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='PEARLS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.IntegerField(default=-1)),
                ('centroid_x', models.FloatField()),
                ('centroid_y', models.FloatField()),
                ('centroid_z', models.FloatField()),
                ('centroid_r', models.FloatField()),
                ('centroid_s', models.IntegerField()),
                ('centroid_c', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Beads',
        ),
        migrations.DeleteModel(
            name='Points',
        ),
    ]
