# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-25 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beads', '0004_auto_20180819_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='pearls',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pearls',
            name='pearl_id',
            field=models.IntegerField(default=-1),
        ),
    ]
